

# This file was *autogenerated* from the file test.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_8483573517 = Integer(8483573517); _sage_const_2 = Integer(2); _sage_const_9 = Integer(9); _sage_const_1253 = Integer(1253); _sage_const_1321 = Integer(1321); _sage_const_7424 = Integer(7424); _sage_const_2000100 = Integer(2000100); _sage_const_243898019 = Integer(243898019); _sage_const_28 = Integer(28); _sage_const_14324 = Integer(14324); _sage_const_4626 = Integer(4626); _sage_const_4645593 = Integer(4645593); _sage_const_10783807739 = Integer(10783807739); _sage_const_16486308645705 = Integer(16486308645705); _sage_const_4 = Integer(4); _sage_const_20412485227 = Integer(20412485227); _sage_const_13 = Integer(13); _sage_const_3319 = Integer(3319); _sage_const_22639 = Integer(22639); _sage_const_109903 = Integer(109903); _sage_const_12977017 = Integer(12977017); _sage_const_383229727 = Integer(383229727); _sage_const_199 = Integer(199); _sage_const_18979 = Integer(18979); _sage_const_49 = Integer(49); _sage_const_10903 = Integer(10903); _sage_const_5290657 = Integer(5290657); _sage_const_10833080827 = Integer(10833080827); _sage_const_22921299619447 = Integer(22921299619447)
a =  [_sage_const_1 ,
 _sage_const_8483573517 ,
 _sage_const_2 ,
 _sage_const_9 ,
 _sage_const_1253 ,
 _sage_const_1321 ,
 _sage_const_7424 ,
 _sage_const_2000100 ,
 _sage_const_243898019 ,
 _sage_const_28 ,
 _sage_const_14324 ,
 _sage_const_2 ,
 _sage_const_4626 ,
 _sage_const_4645593 ,
 _sage_const_10783807739 ,
 _sage_const_16486308645705 ]
pp = [_sage_const_4 ,
 _sage_const_20412485227 ,
 _sage_const_9 ,
 _sage_const_13 ,
 _sage_const_3319 ,
 _sage_const_22639 ,
 _sage_const_109903 ,
 _sage_const_12977017 ,
 _sage_const_383229727 ,
 _sage_const_199 ,
 _sage_const_18979 ,
 _sage_const_49 ,
 _sage_const_10903 ,
 _sage_const_5290657 ,
 _sage_const_10833080827 ,
 _sage_const_22921299619447 ]

test = CRT(a, pp)
print(test)

mod = lcm(pp)
print(mod)

